Sana09/Models/ErrorViewModel.cs
namespace Sana09.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Sana09/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Sana09.Models;
using System.Diagnostics;

namespace Sana09.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Sana()
        {
            return View();
        }

        public IActionResult Morozov()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Sana09/Controllers/NewController.cs
using Microsoft.AspNetCore.Mvc;

namespace Sana09.Controllers
{
    public class NewController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Fict()
        {
            return View();
        }
        public IActionResult DeanFict()
        {
            return View();
        }
    }
}

Sana09/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 class-background-color-black">Welcome, dear guest</h1>
    <p>Learn about <a href="https://ztu.edu.ua/">ZTU</a>.</p>
    <a href="../New/Index"><div class="button">New</div></a>
</div>

Sana09/Views/Home/Morozov.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<img class="images" src="https://scontent.fods8-1.fna.fbcdn.net/v/t39.30808-1/425588948_25119702470961643_4438419881699715371_n.jpg?stp=dst-jpg_s200x200&_nc_cat=100&ccb=1-7&_nc_sid=5f2048&_nc_ohc=kgILZJD6OKUAX_NcJXw&_nc_ht=scontent.fods8-1.fna&oh=00_AfCPRuHHPhbz308hMtPGbJz2FFaGQyTHA_3SwH_9GRZiLg&oe=660AA766" 
    alt="Morozov" />
<p>Morozov's <a href="https://ztu.edu.ua/teacher/323.html">ZTU</p></Morozov's></a>
<p>Morozov's <a href="https://www.facebook.com/morozov.andriy/?locale=uk_UA">Facebook</p></a>
@{
}

Sana09/Views/Home/Sana.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<a href="https://www.sana-commerce.com/">
    <img class="images" src="https://s.dou.ua/CACHE/images/img/static/companies/NEW_sana_logo_diapositive_-_red_main/dd5f1f943411d31a26ffeb1a8b8d8d9c.png" alt="Sana">
    </img></a>
<p class="class-background-color-black">
    Sana Commerce is a B2B e-commerce software company headquartered in the Van Nelle Factory,
    located in Rotterdam, The Netherlands. Sana Commerce was founded in 2008 by Jan Kees de Jager and Karel van der Woude</p>
@{
}

Sana09/Views/New/DeanFict.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<p class="new-class">It is dean of the Faculty FICT</p>
<a href="https://ztu.edu.ua/teacher/132.html?type=dean"><img class="images" src="https://ztu.edu.ua/site/photos/staff/2389.png" alt="Fict" /></a>
@{
}

Sana09/Views/New/Fict.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<p class="new-class">It is FICT</p>
<a href="https://ztu.edu.ua/department/3.html"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLx5BYNaIQ4zdRHqutBwp61IQy8ATjkWK8vnuoXGqXOg&s" alt="Fict" /></a>
@{
}

Sana09/Views/New/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<p class="new-class">It is new controller</p>
<a href="../Home/Index"><div class="button">Home</div></a>
@{
}

Sana09/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sana09</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sana09.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sana09</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Sana">Sana</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Morozov">Morozov</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="New" asp-action="FICT">Fict</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="New" asp-action="DeanFict">Dean FICT</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Sana09 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>